### PR TITLE
Add seed to ChatCompletionRequest

### PR DESCRIPTION
**Pull request by malteneuss**
Add these field that are also usable by Ollama; tested locally.

@nickhs I overlooked that there already two similar PRs xD. It seems to be an important issue for some. It would be great to have this as it helps for integrating Ollama/Openai into apps. Feel free to modify this PR, request changes etc.

### CODE REVIEW

**Comment by nickhs** [comment]
Hi @malteneuss thanks for sending this in! I merged https://github.com/agrafix/openai-hs/pull/22 - if you want to rebase off main and include only the `seed` change I can merge this in!

**Comment by malteneuss** [comment]
Done

**Review by nickhs — APPROVED** [review]

**Comment by nickhs** [comment]
thank you!

**Comment by malteneuss** [comment]
Anything missing to get this merged?

**Comment by nickhs** [comment]
merged! thanks again!

**Pull request merged**
